### ISSUE TITLE
if num of user is more than 100, Asynctransfer crashes

### ISSUE THREAD

**Issue by juztas** [dmwm/AsyncStageout#4426] opened 2015-08-07 20:40 UTC
Today was a lot of users and pool size is 100 and than it become more than 100, ASyncTransfer component crashed with couchdb error.
```
ERROR:AsyncTransfer-Worker-hdelanno:Timeout in export X509_USER_PROXY=/data/srv/asyncstageout/state/asyncstageout/creds/427f8a89aaa69c4439b9d9b27b87c7506e02ff8b ; source /data/srv/tmp.sh ; glite-delegation-init -s https://fts3.cern.ch:8443 execution.
DEBUG:AsyncTransfer-Worker-hdelanno:User proxy of hdelanno could not be delagated! Trying next time.
INFO:AsyncTransfer-Worker-hdelanno:Transfers completed
ERROR:AsyncTransfer-Worker-kbutanov:Timeout in export X509_USER_PROXY=/data/srv/asyncstageout/state/asyncstageout/creds/8123da6528ec4abd24562a99b4f2b0ec556bed0b ; source /data/srv/tmp.sh ; glite-delegation-init -s https://fts3.cern.ch:8443 execution.
DEBUG:AsyncTransfer-Worker-kbutanov:User proxy of kbutanov could not be delagated! Trying next time.
INFO:AsyncTransfer-Worker-kbutanov:Transfers completed
ERROR:AsyncTransfer-Worker-mschoene:Timeout in export X509_USER_PROXY=/data/srv/asyncstageout/state/asyncstageout/creds/c572a4db89646624afbc2421b90324788ef3d873 ; source /data/srv/tmp.sh ; glite-delegation-init -s https://fts3.cern.ch:8443 execution.
DEBUG:AsyncTransfer-Worker-mschoene:User proxy of mschoene could not be delagated! Trying next time.
INFO:AsyncTransfer-Worker-mschoene:Transfers completed
ERROR:root:Error in worker algorithm (1):
Backtrace:
  <AsyncStageOut.TransferDaemon.TransferDaemon instance at 0x2d47e60> CouchUnauthorisedError - reason: Unauthorized, data: {} result: None  File "/data/srv/asyncstageout/v1.0.3pre8/sw.pre.riahi/slc6_amd64_gcc481/cms/asyncstageout/1.0.3pre8/lib/python2.6/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 172, in __call__
    self.algorithm(parameters)
  File "/data/srv/asyncstageout/v1.0.3pre8/sw.pre.riahi/slc6_amd64_gcc481/cms/asyncstageout/1.0.3pre8/lib/python2.6/site-packages/AsyncStageOut/TransferDaemon.py", line 126, in algorithm
    users = self.active_users(self.db)
  File "/data/srv/asyncstageout/v1.0.3pre8/sw.pre.riahi/slc6_amd64_gcc481/cms/asyncstageout/1.0.3pre8/lib/python2.6/site-packages/AsyncStageOut/TransferDaemon.py", line 171, in active_users
    sorted_users = self.factory.loadObject(self.config.algoName, args = [self.config, self.logger, users['rows'], self.config.pool_size], getFromCache = False, listFlag = True)
  File "/data/srv/asyncstageout/v1.0.3pre8/sw.pre.riahi/slc6_amd64_gcc481/cms/asyncstageout/1.0.3pre8/lib/python2.6/site-packages/WMCore/WMFactory.py", line 77, in loadObject
    classinstance = obj(*args)
  File "/data/srv/asyncstageout/v1.0.3pre8/sw.pre.riahi/slc6_amd64_gcc481/cms/asyncstageout/1.0.3pre8/lib/python2.6/site-packages/AsyncStageOut/SchedPlugins/FIFOPriority.py", line 49, in __init__
    Algo.__init__(self, config, logger, users, pool_size)
  File "/data/srv/asyncstageout/v1.0.3pre8/sw.pre.riahi/slc6_amd64_gcc481/cms/asyncstageout/1.0.3pre8/lib/python2.6/site-packages/AsyncStageOut/SchedPlugins/Algo.py", line 22, in __init__
    self.config_db = self.asyncServer.connectDatabase(self.config.config_database)
  File "/data/srv/asyncstageout/v1.0.3pre8/sw.pre.riahi/slc6_amd64_gcc481/cms/asyncstageout/1.0.3pre8/lib/python2.6/site-packages/WMCore/Database/CMSCouch.py", line 837, in connectDatabase
    return self.createDatabase(dbname)
  File "/data/srv/asyncstageout/v1.0.3pre8/sw.pre.riahi/slc6_amd64_gcc481/cms/asyncstageout/1.0.3pre8/lib/python2.6/site-packages/WMCore/Database/CMSCouch.py", line 819, in createDatabase
    self.put("/%s" % urllib.quote_plus(dbname))
  File "/data/srv/asyncstageout/v1.0.3pre8/sw.pre.riahi/slc6_amd64_gcc481/cms/asyncstageout/1.0.3pre8/lib/python2.6/site-packages/WMCore/Services/Requests.py", line 125, in put
  File "/data/srv/asyncstageout/v1.0.3pre8/sw.pre.riahi/slc6_amd64_gcc481/cms/asyncstageout/1.0.3pre8/lib/python2.6/site-packages/WMCore/Database/CMSCouch.py", line 116, in makeRequest
    getattr(e, "reason", None), data)
  File "/data/srv/asyncstageout/v1.0.3pre8/sw.pre.riahi/slc6_amd64_gcc481/cms/asyncstageout/1.0.3pre8/lib/python2.6/site-packages/WMCore/Database/CMSCouch.py", line 129, in checkForCouchError
    raise CouchUnauthorisedError(reason, data, result)

INFO:root:>>>Terminating worker threads
ERROR:root:Error in event loop (2): <AsyncStageOut.TransferDaemon.TransferDaemon instance at 0x2d47e60> CouchUnauthorisedError - reason: Unauthorized, data: {} result: None
Backtrace:
  File "/data/srv/asyncstageout/v1.0.3pre8/sw.pre.riahi/slc6_amd64_gcc481/cms/asyncstageout/1.0.3pre8/lib/python2.6/site-packages/WMCore/WorkerThreads/BaseWorkerThread.py", line 198, in __call__
    raise ex

INFO:root:Worker thread <AsyncStageOut.TransferDaemon.TransferDaemon instance at 0x2d47e60> terminated
```
Currently pool size is increased to 300 and we need to keep eye on it until fix is in place.

Also during that I executed manage status, and it was showing that AsyncTransfer component is running, its not correct, but it is lower priority.

**Comment by HassenRiahi** [comment] 2015-08-07 20:53
The expected behavior is when the pool size is set to 100 and the number of users becomes > 100 the ASO should keep users in his queue and not crashing.

**Comment by HassenRiahi** [comment] 2016-02-03 09:02
It happened again this morning since it was not fixed.

**Comment by HassenRiahi** [comment] 2016-04-12 12:56
The bug has been fixed and tested here: https://github.com/dmwm/AsyncStageout/pull/4485. Closing the ticket.

**Closed by HassenRiahi** 2016-04-12 12:56 UTC
Labels: Critical
