### ISSUE TITLE
Exception on get_tfc_rule for a single site, lock down ASO 

### ISSUE THREAD

**Issue by dciangot** [dmwm/AsyncStageout#4512] opened 2016-07-25 06:33 UTC
https://cms-logbook.cern.ch/elog/Analysis+Operations/1011?mail0=24%20recipients

We have to fix the behaviour on the management of the exceptions from get_tfc_rule in the TransferDaemon. I'm working on it.

Just for the record the error in the example reported above is:
2016-07-25 06:08:44 GMT:WARNING:Service:PhEDEx: The cachefile /data/srv/asyncstageout/v1.0.5pre3/install/asyncstageout/AsyncTransfer/.wmcore_cache/.wmcore_cache_500/requests/cmsweb.cern.ch/2749847966300314983_GET_tfc does not exist and the service at https://cmsweb.cern.ch/phedex/datasvc/xml/prod/tfc is unavailable - it returned 400 because Bad Request
 with result: The 'NODE' parameter ("\T3_CH_Volunteer\") to (eval) did not pass the 'node' callback\n\n

**Comment by belforte** [comment] 2016-07-25 06:48
@mmascher @emaszs do you know why this was not spotted in CRAB already ? I thought we parse LFN's there as well, if nothing else to validate stageout destination.

**Comment by belforte** [comment] 2016-07-26 14:57
hmmmm. Getting the TFC from phedex for that site is currently working for me.

belforte@lxplus096/~> curl -ks "https://cmsweb.cern.ch/phedex/datasvc/perl/prod/tfc?node=T3_CH_Volunteer"
$VAR1 = {
          'PHEDEX' => {
                        'REQUEST_DATE' => '2016-07-26 14:56:17 UTC',
                        'STORAGE-MAPPING' => {
                                               'ARRAY' => [
                                                            {
                                                              'RESULT' => 'http://data-bridge-test.cern.ch/myfed/cms-boinc/output/$1',
                                                              'ELEMENT_NAME' => 'lfn-to-pfn',
                                                              'PROTOCOL' => 'http',
                                                              'PATH-MATCH' => '/+store/(.*)'
                                                            },
                                                            {
                                                              'RESULT' => 'davs://data-bridge-test.cern.ch/myfed/cms-boinc/output/$1',
                                                              'ELEMENT_NAME' => 'lfn-to-pfn',
                                                              'PROTOCOL' => 'https',
                                                              'PATH-MATCH' => '/+store/(.*)'
                                                            },
                                                            {
                                                              'RESULT' => 'davs://data-bridge-test.cern.ch/myfed/cms-boinc/output/$1',
                                                              'ELEMENT_NAME' => 'lfn-to-pfn',
                                                              'PROTOCOL' => 'srmv2',
                                                              'PATH-MATCH' => '/+store/(.*)'
                                                            }
                                                          ]
                                             },
                        'REQUEST_CALL' => 'tfc',
                        'REQUEST_URL' => 'http://cmsweb.cern.ch:7001/phedex/datasvc/perl/prod/tfc',
                        'CALL_TIME' => '0.00252',
                        'REQUEST_VERSION' => '2.3.22',
                        'REQUEST_TIMESTAMP' => '1469544977.06363',
                        'INSTANCE' => 'prod'
                      }
        };
belforte@lxplus096/~>

**Comment by belforte** [comment] 2016-07-26 16:15
@dciangot do you have example error message ? Also I think you put some fix in, what did you exactly change ?

**Comment by belforte** [comment] 2016-07-26 16:19
I am very suspicious of:  `The 'NODE' parameter ("\T3_CH_Volunteer\")`
I can reproduce the message with 
`curl -ks "https://cmsweb.cern.ch/phedex/datasvc/xml/prod/tfc?NODE=\T3_CH_Volunteer"`
note the extra backslash. While this is OK:
`curl -ks "https://cmsweb.cern.ch/phedex/datasvc/xml/prod/tfc?NODE=T3_CH_Volunteer"`

**Comment by belforte** [comment] 2016-07-26 16:23
more precisely:
```
belforte@lxplus096/~> curl -ks 'https://cmsweb.cern.ch/phedex/datasvc/xml/prod/tfc?NODE=\T3_CH_Volunteer\' 
The 'NODE' parameter ("\T3_CH_Volunteer\") to (eval) did not pass the 'node' callback\
```

**Comment by dciangot** [comment] 2016-07-27 10:35
Ok, thanks Stefano, following your hints I found the issue in the logs (*).
You can find there the moment of the issue and the situation just before.

So at 12:15:42 GMT   "T3_CH_Volunteer" was already in the list of active sites and no problem there in fact ASO return correctly the message:
data: {'node': 'T3_CH_Volunteer'}

While at 12:15:53 GMT in the list of active sites, '\\T3_CH_Volunteer\\'  appeared and caused the issue we saw, locking down ASO.

What still no clear to me is if crab put that in couch wrongly or either couch misreturn the value to ASO. The latter would be really weird since in the list of active sites returned by couch there are both   "T3_CH_Volunteer" and "\\T3_CH_Volunteer\\".


(*)
> stderr.log-20160725.gz:2016-07-24 12:15:42 GMT:DEBUG:TransferDaemon:root: Active sites are: ['T1_DE_KIT_Disk', 'T1_ES_PIC_Disk', 'T1_FR_CCIN2P3_Disk', 'T1_IT_CNAF_Disk', 'T1_RU_JINR', 'T1_RU_JINR_Disk', 'T1_UK_RAL_Disk', 'T1_US_FNAL_Disk', 'T2_AT_Vienna', 'T2_BE_IIHE', 'T2_BE_UCL', 'T2_BR_SPRACE', 'T2_BR_UERJ', 'T2_CH_CERN', 'T2_CH_CSCS', 'T2_CN_Beijing', 'T2_DE_DESY', 'T2_DE_RWTH', 'T2_EE_Estonia', 'T2_ES_CIEMAT', 'T2_ES_IFCA', 'T2_FI_HIP', 'T2_FR_GRIF_IRFU', 'T2_FR_GRIF_LLR', 'T2_FR_IPHC', 'T2_GR_Ioannina', 'T2_HU_Budapest', 'T2_IN_TIFR', 'T2_IT_Bari', 'T2_IT_Legnaro', 'T2_IT_Pisa', 'T2_IT_Rome', 'T2_KR_KNU', 'T2_PK_NCP', 'T2_PL_Swierk', 'T2_PT_NCG_Lisbon', 'T2_RU_IHEP', 'T2_RU_ITEP', 'T2_RU_JINR', 'T2_TR_METU', 'T2_TW_NCHC', 'T2_UA_KIPT', 'T2_UK_London_Brunel', 'T2_UK_London_IC', 'T2_UK_SGrid_Bristol', 'T2_UK_SGrid_RALPP', 'T2_US_Caltech', 'T2_US_Florida', 'T2_US_MIT', 'T2_US_Nebraska', 'T2_US_Purdue', 'T2_US_UCSD', 'T2_US_Vanderbilt', 'T2_US_Wisconsin', 'T3_BG_UNI_SOFIA', 'T3_CH_CERN_CAF', 'T3_CH_PSI', 'T3_CH_Volunteer', 'T3_FR_IPNL', 'T3_HU_Debrecen', 'T3_IR_IPM', 'T3_IT_Bologna', 'T3_IT_Perugia', 'T3_IT_Trieste', 'T3_KR_KISTI', 'T3_KR_UOS', 'T3_MX_Cinvestav', 'T3_TW_NCU', 'T3_TW_NTU_HEP', 'T3_UK_London_QMUL', 'T3_UK_ScotGrid_GLA', 'T3_UK_SGrid_Oxford', 'T3_US_Baylor', 'T3_US_Brown', 'T3_US_Colorado', 'T3_US_Cornell', 'T3_US_FIT', 'T3_US_FNALLPC', 'T3_US_OSU', 'T3_US_PuertoRico', 'T3_US_Rice', 'T3_US_Rutgers', 'T3_US_TAMU', 'T3_US_UCR', 'T3_US_UMD', 'T3_US_UMiss']
> stderr.log-20160725.gz:	data: {'node': 'T3_CH_Volunteer'}
> stderr.log-20160725.gz:2016-07-24 12:15:53 GMT:DEBUG:TransferDaemon:root: Active sites are: ['\\T3_CH_Volunteer\\', 'T1_DE_KIT_Disk', 'T1_ES_PIC_Disk', 'T1_FR_CCIN2P3_Disk', 'T1_IT_CNAF_Disk', 'T1_RU_JINR', 'T1_RU_JINR_Disk', 'T1_UK_RAL_Disk', 'T1_US_FNAL_Disk', 'T2_AT_Vienna', 'T2_BE_IIHE', 'T2_BE_UCL', 'T2_BR_SPRACE', 'T2_BR_UERJ', 'T2_CH_CERN', 'T2_CH_CSCS', 'T2_CN_Beijing', 'T2_DE_DESY', 'T2_DE_RWTH', 'T2_EE_Estonia', 'T2_ES_CIEMAT', 'T2_ES_IFCA', 'T2_FI_HIP', 'T2_FR_GRIF_IRFU', 'T2_FR_GRIF_LLR', 'T2_FR_IPHC', 'T2_GR_Ioannina', 'T2_HU_Budapest', 'T2_IN_TIFR', 'T2_IT_Bari', 'T2_IT_Legnaro', 'T2_IT_Pisa', 'T2_IT_Rome', 'T2_KR_KNU', 'T2_PK_NCP', 'T2_PL_Swierk', 'T2_PT_NCG_Lisbon', 'T2_RU_IHEP', 'T2_RU_ITEP', 'T2_RU_JINR', 'T2_TR_METU', 'T2_TW_NCHC', 'T2_UA_KIPT', 'T2_UK_London_Brunel', 'T2_UK_London_IC', 'T2_UK_SGrid_Bristol', 'T2_UK_SGrid_RALPP', 'T2_US_Caltech', 'T2_US_Florida', 'T2_US_MIT', 'T2_US_Nebraska', 'T2_US_Purdue', 'T2_US_UCSD', 'T2_US_Vanderbilt', 'T2_US_Wisconsin', 'T3_BG_UNI_SOFIA', 'T3_CH_CERN_CAF', 'T3_CH_PSI', 'T3_CH_Volunteer', 'T3_FR_IPNL', 'T3_HU_Debrecen', 'T3_IR_IPM', 'T3_IT_Bologna', 'T3_IT_Perugia', 'T3_IT_Trieste', 'T3_KR_KISTI', 'T3_KR_UOS', 'T3_MX_Cinvestav', 'T3_TW_NCU', 'T3_TW_NTU_HEP', 'T3_UK_London_QMUL', 'T3_UK_ScotGrid_GLA', 'T3_UK_SGrid_Oxford', 'T3_US_Baylor', 'T3_US_Brown', 'T3_US_Colorado', 'T3_US_Cornell', 'T3_US_FIT', 'T3_US_FNALLPC', 'T3_US_OSU', 'T3_US_PuertoRico', 'T3_US_Rice', 'T3_US_Rutgers', 'T3_US_TAMU', 'T3_US_UCR', 'T3_US_UMD', 'T3_US_UMiss']
> stderr.log-20160725.gz:	data: {'node': '\\T3_CH_Volunteer\\'}
> stderr.log-20160725.gz: with result: The 'NODE' parameter ("\T3_CH_Volunteer\") to (eval) did not pass the 'node' callback\n\n

**Comment by belforte** [comment] 2016-07-27 10:39
Maybe a "user" manage to slip in a malformed site name which CRAB did not complain about.
Do you have a way to get a task name with the \T3_CH_Volunteer\ ?
Anyhow... which fix is currently deployed ?

**Comment by dciangot** [comment] 2016-10-20 06:51
It happened again yesterday evening. The current fix is ignoring the malformed site. 
Shall we investigate where is it coming from?

**Comment by mmascher** [comment] 2016-10-20 07:45
Hi Diego,

do you know what is the API that fails? I see a T3_CH_Volunteer node in phedex (https://cmsweb.cern.ch/phedex/datasvc/xml/prod/nodes):

```
[...]
<node kind="Disk" se="data-bridge-test.cern.ch" technology="Other" name="T3_CH_Volunteer" id="2166"/>
[...]
```

Anyway, these looks like CMS@home jobs, pretty sure they are not supposed to use ASO.. Probably worth to find the taskname/username and drop a message on cms-cloud.

**Comment by dciangot** [comment] 2016-10-20 07:47
Hi Marco,
 T3_CH_Volunteer is indeed ok, but in couch there is  \T3_CH_Volunteer\ that is not ok.

**Comment by emaszs** [comment] 2016-10-20 08:09
Well in CRAB we don't allow backslashes, the server returns an error. Also, checked in the TaskDB with Jadir, this was the most recent task [*] with the stageout destination "T3_CH_Volunteer". We also didn't find any tasks that had the destination set as "\T3_CH_Volunteer\" which isn't surprising. 

161018_234912:ireid_crab_BPH-RunIISummer15GS-00046_AI

**Comment by dciangot** [comment] 2016-10-20 08:12
Ok, good. So as Marco supposed they are coming from other sources probably.

**Comment by belforte** [comment] 2016-10-20 10:12
I also think that CMS@HOME stages out directly form the WN to T3_CH_Volunteer, but maybe every job uploads metadata anyhow ? Indeed we nee a task name.

@dciangot When you say 'current fix ignores this', is that the fix you put in July, or did you just change things again ? I do not understand what exactly was done to made the problem go away.

**Comment by dciangot** [comment] 2016-10-20 10:45
The same temp patch was done on July but by mistake not propagated to the other aso machine...

In any case it's not a solution, I would rather go for avoiding useless docs to be sended to couch than ignoring them.

**Comment by mmascher** [comment] 2016-10-20 13:49
Ah I see,

what the user is setting unconventionally is the extrajdl parameter:

['+Used_Gatekeeper="volunteer/cms-vol"', '+use_x509userproxy=False',
'+DESIRED_Sites="T3_CH_Volunteer"', '+JOB_CMSSite="T3_CH_Volunteer"',
'+CRAB_AsyncDest="T3_CH_Volunteer"', '+CRAB_StageoutPolicy="remote"',
'+Used_Gatekeeper="boinc.cern.ch"']

Maybe we are escaping things in the wrong way? Emilis, are you already
trying to replicate the issue? Unfortunately I cannot access the
log/schedd..

Cheers,

Marco

**Comment by emaszs** [comment] 2016-10-20 13:56
Huh, interesting, didn't think to look in there. I'll try to replicate it to see what happens to the AsyncDest parameter.

**Comment by belforte** [comment] 2016-10-20 15:15
it does not help debugging that those jobs use a schedd in UK lcggwms02.gridpp.rl.ac.uk 
I looked at TW log for one task[*] and T3_CH_Volunteer appears in the expected way, but I can't checl jobs or postJob logs.
[*]
161018_234912:ireid_crab_BPH-RunIISummer15GS-00046_AI

I'd rather ask : does this happen with all CMS@HOME jobs, or did simply IvanReid manage to get a / too many just once ?

**Comment by emaszs** [comment] 2016-10-20 15:18
Submitted to my VM using a false aso instance, not much luck so far about the escaping, this is my extrajdl in the crabConfig (included a few params just in case):
`config.Debug.extraJDL = ['+DESIRED_Sites="T2_CH_CERN"', '+CRAB_AsyncDest="T2_CH_CERN"', '+CRAB_StageoutPolicy="remote"']`

And this is what it looks like on the taskworker, escaping makes sense:
`u'tm_extrajdl': u'[\'+DESIRED_Sites="T2_CH_CERN"\', \'+CRAB_AsyncDest="T2_CH_CERN"\', \'+CRAB_StageoutPolicy="remote"\']' `

This is what's at the end of the Job.X.submit jdl file, coming from the extraJdl parameter in the crabConfig:
```
+DESIRED_Sites="T2_CH_CERN"
+CRAB_AsyncDest="T2_CH_CERN"
+CRAB_StageoutPolicy="remote"
queue
```

**Comment by emaszs** [comment] 2016-10-20 15:27
@belforte Can't pass the backslashes via the extraJdl either (whether or not they're escaped manually). Also, when we looked at the T3_CH_Volunteer tasks in the DB, they were being submitted fairly regularly during the last year, I think we would've seen this a lot more often were it the fault of CMS@HOME (not entirely sure how it works with crab though)

**Comment by belforte** [comment] 2016-10-20 15:56
so, if this is "something in a blue moon".... let's put a protection in ASO and go on.
Ideally we could set traps so to trigger a special loggin when the \  is detected at wrting or 
reading time.. but.. is it worth ? I do not want to go into .. maybe something changed entry in 
Couch after it was written OK and before it was read BAD....

**Comment by belforte** [comment] 2016-10-29 06:20
@dciangot can you put a reference in here to the code fix ? I think we can then check which message to print if any and close

**Comment by belforte** [comment] 2017-02-21 21:31
@dciangot please see my previous (last) comment on Oct 2016. Can we close the loop and close ?

**Comment by dciangot** [comment] 2017-02-22 08:53
I'm pretty sure the fix is there, but I'm trying to find out the reference. Hope to be back soon.

**Comment by dciangot** [comment] 2017-02-22 10:18
ASO is know getting all the site tfc at the beginning. And in case of an invalid sitename the transfer will be put in failed by the transferworker(**). 
I think we can close it if there are no further comments.

(*) 
https://github.com/dmwm/AsyncStageout/blob/master/src/python/AsyncStageOut/TransferDaemon.py#L118-L139

(**)
https://github.com/dmwm/AsyncStageout/blob/master/src/python/AsyncStageOut/TransferWorker.py#L309-L333

**Comment by belforte** [comment] 2017-02-22 13:06
thanks

**Closed by belforte** 2017-02-22 13:06 UTC
Labels: question
